### ISSUE TITLE
Improve travis build pipeline

### ISSUE THREAD

**Issue by maschino** [environment-agency-austria/react-ocean-forms#19]
Currently travis is creating the workspace at each build step (build, lint, test) - this includes creating the node_modules folder, preparing yarn etc.

This isn't necessary in our case, we could reuse the workspace and just run the three commands one after another. I guess this would speed up our build pipeline a bit?

**Comment by maschino** [comment]
@christophka maybe you have more experience with travis than I do? Any ideas? 😃

**Comment by christophka** [comment]
Well, I just did a quick research and the first thing that came up is this: https://docs.travis-ci.com/user/caching/#yarn-cache

**Comment by maschino** [comment]
Okay I guess I'm an idiot 🙄 It's right there in the travis documentation:
https://docs.travis-ci.com/user/build-stages/#how-do-build-stages-work

So I guess we should change the travis.yml to have one stage with three scripts?

**Comment by christophka** [comment]
if i group the thinks that are happening logically, I would have something like an "Q&A" or "test" stage with the lint and test script.
Then there would be a build stage, that is only executed, if the "test" stage executes without any failure.
But yes, we could also just but all the scripts in one stage 👍

**Comment by maschino** [comment]
Sounds good! Ideally we would publish to npm automatically from travis as well - but I'm not sure how to do that currently.

**Comment by christophka** [comment]
https://docs.travis-ci.com/user/build-stages/deploy-npm/

**Comment by maschino** [comment]
Hmmm 🤔 

But what would trigger that script? A release / tag on github?

**Comment by christophka** [comment]
And in the configuration, you can also execute scripts, only if you are on a current branch (see here: https://docs.travis-ci.com/user/build-stages/#specifying-stage-order-and-conditions).
We could say, that any changes (simple commits or pull requests) on master always result in a deploy on npm.

**Comment by christophka** [comment]
Shall I have a look on what our possibilities are on that matter? If so, I will assign the issue to me 🤓

**Comment by maschino** [comment]
I'm not sure if that would work if the package.json version stays the same. npm refuses to overwrite packages with existing versions. We could do that with nightly builds (tagged as `@next` on npm).

Sure, assign yourself :D
